version: "3.3"
services:
  postgresql:
    image: postgres:latest
    restart: always
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    #    env_file: ./.env-postgres
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: sqlbootcamp
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "1234:8080"
